# Deploy to GitHub Pages
# This workflow is triggered in two ways:
# 1. When pushing a tag that starts with 'rc-' (e.g., rc-v1.0.0)
# 2. Manually via the GitHub Actions interface (workflow_dispatch)
name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'rc-**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          find . -type f -name "*.py" | sort

      - name: Generate Graph
        run: |
          mkdir -p output
          # Check if the script exists before running it
          if [ -f scripts/generate_graph.py ]; then
            python scripts/generate_graph.py
          elif [ -f generate_graph.py ]; then
            python generate_graph.py
          else
            echo "Error: generate_graph.py not found"
            exit 1
          fi

      - name: Copy graph.json to web directory
        run: |
          if [ -f output/graph.json ]; then
            mkdir -p web
            cp output/graph.json web/
          else
            echo "Error: graph.json not generated"
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: web
          clean: true